services:
  shinobi-code-api:
    container_name: shinobi-code-api
    image: ghcr.io/shinobi-c0de/shinobi-code-api:latest
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped
